### ISSUE TITLE
Support branch name containing /

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/repo-sync-api#2]
**Describe the bug**
If the trigger branch for the synchronization contains a `/` it'll error on the API side (most likely on folder creation).

**Expected behavior**
It should normally create the folder where is located the data of the relevant branch.

**To Reproduce**
1. create a new repository based off of `template-synced-repo`
2. create a new branch named `release/v1`
3. this will trigger an error on the server side

**Error message**
```bash
0|repo-sync-api  | Error: ENOENT: no such file or directory, chdir '/home/repositories/test' -> '/home/repositories/test/release/v1'
0|repo-sync-api  |     at wrappedChdir (internal/bootstrap/switches/does_own_process_state.js:115:14)
0|repo-sync-api  |     at process.chdir (internal/worker.js:86:5)
0|repo-sync-api  |     at module.exports (/home/repositories/repo-sync-api/master/utils/pull.js:5:11)
0|repo-sync-api  |     at module.exports (/home/repositories/repo-sync-api/master/utils/sync.js:20:7)
0|repo-sync-api  |     at /home/repositories/repo-sync-api/master/index.js:22:3
0|repo-sync-api  |     at Layer.handle [as handle_request] (/home/repositories/repo-sync-api/master/node_modules/express/lib/router/layer.js:95:5)
0|repo-sync-api  |     at next (/home/repositories/repo-sync-api/master/node_modules/express/lib/router/route.js:137:13)
0|repo-sync-api  |     at Route.dispatch (/home/repositories/repo-sync-api/master/node_modules/express/lib/router/route.js:112:3)
0|repo-sync-api  |     at Layer.handle [as handle_request] (/home/repositories/repo-sync-api/master/node_modules/express/lib/router/layer.js:95:5)
0|repo-sync-api  |     at /home/repositories/repo-sync-api/master/node_modules/express/lib/router/index.js:281:22
```

**Note**
We may not want this behavior and should maybe limit to branch names not containing `/`

**Comment by alexlemaire** [comment]
Fixed, closing now.
